from datetime import datetime
from decimal import Decimal

from fastapi.testclient import TestClient

from app.domain.market import (
    Candle,
    CandleIdentity,
    CandleInterval,
    MarketDataSnapshot,
)
from app.main import app
from app.storage.database import initialize_database
from app.storage.market_snapshot_repository import (
    save_snapshot,
)

from app.ai.fake_provider import FakeAIProvider
from app.main import app, get_ai_provider


client = TestClient(app)
app.dependency_overrides[
    get_ai_provider
] = lambda: FakeAIProvider()


def create_test_snapshot() -> MarketDataSnapshot:
    return MarketDataSnapshot(
        instrument_id="TEST:NSE:SBIN:API",
        interval=CandleInterval.FIVE_MINUTES,
        data_version=1,
        latest_candle_timestamp=datetime(
            2026,
            8,
            28,
            9,
            15,
        ),
        candles=(
            Candle(
                identity=CandleIdentity(
                    instrument_id="TEST:NSE:SBIN:API",
                    interval=CandleInterval.FIVE_MINUTES,
                    timestamp=datetime(
                        2026,
                        8,
                        28,
                        9,
                        15,
                    ),
                ),
                open=Decimal("100"),
                high=Decimal("110"),
                low=Decimal("90"),
                close=Decimal("105"),
                volume=1000,
                source="test",
                fetched_at=datetime(
                    2026,
                    8,
                    28,
                    9,
                    16,
                ),
            ),
        ),
        snapshot_hash="test-api-snapshot-001",
    )


def test_health_check():
    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {
        "status": "ok",
    }


def test_create_analysis():
    initialize_database()

    snapshot = create_test_snapshot()
    save_snapshot(snapshot)

    response = client.post(
        "/analysis",
        json={
            "snapshot_hash": snapshot.snapshot_hash,
            "prompt": "Analyze this stock.",
        },
    )

    assert response.status_code == 200

    data = response.json()

    assert data["snapshot_hash"] == snapshot.snapshot_hash
    assert data["instrument_id"] == snapshot.instrument_id
    assert data["data_version"] == 1
    assert "analysis_id" in data
    
    assert data["action"] == "hold"
    assert data["confidence"] == 50
    assert data["summary"] == "Fake analysis response."
    assert data["reasons"] == [
        "This response is generated by the fake provider."
    ]


def test_create_analysis_returns_404_for_missing_snapshot():
    initialize_database()

    response = client.post(
        "/analysis",
        json={
            "snapshot_hash": "missing-snapshot",
            "prompt": "Analyze this stock.",
            "model": "test-model",
        },
    )

    assert response.status_code == 404
    assert response.json() == {
        "detail": "Market snapshot not found",
    }