from app.ai.provider import AIProvider


class FakeAIProvider(AIProvider):
    def generate(
        self,
        *,
        prompt: str,
        model: str,
    ) -> str:
        return """
        {
            "action": "hold",
            "confidence": 50,
            "summary": "Fake analysis response.",
            "reasons": [
                "This response is generated by the fake provider."
            ]
        }
        """
        
        