from app.ai.provider import AIProvider


class FakeAIProvider(AIProvider):
    def generate(
        self,
        *,
        prompt: str,
        model: str,
    ) -> str:
        return (
            f"Fake analysis generated by {model} "
            f"for prompt: {prompt}"
        )
        
        
        